### ISSUE TITLE
Compasses shown mirrored

### ISSUE THREAD

**Issue by phl0** [schrockwell/hamsat_ex#69]
Since a few days the compasses on pass predictions appear to be mirrored:

![Screenshot from 2024-01-29 21-54-32](https://github.com/schrockwell/hamsat_ex/assets/7112907/726324c0-290d-45ed-aca0-79f605a610a7)

Feels a bit strange to have 90° azimuth to the left ... Can you pls explain or correct this?

**Comment by magicbug** [comment]
Can confirm seeing the same here

**Comment by schrockwell** [comment]
This is intentional, because the graph represents the sky, and when you look up at the sky, east and west are swapped. Star charts use this same configuration. 

I'd argue that it is actually more correct than the "regular" display, even if it appears confusing at first. But I'm not steadfast on it quite yet.
